[package]
name = "rtest"
version = "0.1.0"
edition = "2021"

[dependencies]
parquet = "53.2.0"
anyhow = "1.0.91"
arrow-odbc = "13.0.0"
toml = "0.8.19"
clap = { version = "4.5.20", features = ["derive"] }
